# Generated by Django 4.2.7 on 2023-11-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
